# baseurl = "https://devcows.github.io/hugo-universal-theme/" # Configure URL. if using gh-pages https://github.com/<username>/hugo-universal-theme URL: https://<username>.github.io/hugo-universal-theme/
baseURL = "https://schwartzlab-methods.github.io/hugo-universal-theme/"
title = "Schwartz Lab"
theme = "hugo-universal-theme"
themesDir = "./themes"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

[menu]


# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Research"
    identifier = "menu.research"
    url        = "/research/"
    weight     = 2

[[menu.main]]
    identifier = "software"
    name       = "Software"
    url        = "/software/"
    weight     = 3

[[menu.main]]
    name       = "Publications"
    identifier = "menu.publications"
    url        = "/publications/"
    weight     = 4

[[menu.main]]
    identifier = "team"
    name       = "Our Team"
    url        = "/team/"
    weight     = 5

[[menu.main]]
    identifier = "positions"
    name       = "Open Positions"
    url        = "/positions/"
    weight     = 6

[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 7

[[menu.main]]
    name       = "News"
    identifier = "menu.blog"
    url        = "/blog/"
    weight     = 8

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/GregorySchwartz"
    #url = "https://github.com/schwartzlab-methods"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Twitter"
    url = "http://twitter.com/Schwartastic"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 3
    name = "Email"
    url = "mailto:gregory.schwartz@uhnresearch.ca"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Gregory Schwartz"
    #defaultKeywords = ["devows", "hugo", "go"]
    mainSections = ["blog"]
    defaultDescription = "Schwartz Lab website"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "Schwartastic" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"
    email = "gregory.schwartz@uhnresearch.ca"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = ""
    contact_form_ajax = false

    enableRecaptchaInContactForm = false

    about_us = "<p>We are a computational lab focused on the development of new methods and algorithms to ultimately improve cancer treatment.</p>"
    copyright = ""

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    disabled_logo = true
    logo_text = "Schwartz Lab"

    logo = ""
    logo_small = ""
    address = """<p class="text-uppercase"><strong>Schwartz Lab</strong>
        <br>The Princess Margaret Cancer Centre
        <br>University Health Network
        <br>Toronto
        <br>
        <strong>Canada</strong>
      </p>
      """

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us at gregory.schwartz@uhnresearch.ca</p>
      <p class="hidden-md hidden-lg">
      <a href="mailto:gregory.schwartz@uhnresearch.ca" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 1
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonals]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = false
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = ""
    subtitle = ""

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "Interested in joining us?"
    subtitle = "We are always looking for talented individuals!"
    link_url = "https://schwartzlab-methods.github.io/positions/"
    link_text = "Join Us"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "News"
    subtitle = ""
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[markup.goldmark.renderer]
unsafe = true